### ISSUE TITLE
Error under item 5.Correlate text

### ISSUE THREAD

**Issue by rishank1312** [IBM/watson-document-co-relation#13]
Hi Balaji
Thanks for your earlier response.I converted the pdf files into .txt files and ran the code. .but it is still throwing error under item 5 which is correlate text..The error has to do with sampleconfigfilename..kindly explain what is sample config filename..and which.txt file I have to provide there.
Also please specify what is this error. Is there any other .txt file that I need to provide under sample configfilename. If yes then what/which?
The error says:
**ClientException: Object GET failed: https://dal.objectstorage.open.softlayer.com/v1/AUTH_feddc56178904edabf6d7bf96b773f5f/DefaultProjectrishank1312gmailcomc3di/sample_config.txt 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<**
Regards
Rishank

**Comment by balajikadambi** [comment]
HI Rishank,

Please refer to Sec 4 in the README. 

If you have uploaded your own configuration file, please ensure it is uploaded to Object Storage. It should be visible when you click the 10-01 icon.

Then see "Fix-up file names for your own data and configuration files." to change the configuration file name if it is different from sample_config.txt.

Kindly go through the README in detail.

Thanks,
Balaji

**Comment by balajikadambi** [comment]
Closing issue. Please open a new issue if required.
