### ISSUE TITLE
error in 4.1 section

### ISSUE THREAD

**Issue by lujjiang** [IBM/watson-document-co-relation#14]
KeyErrorTraceback (most recent call last)
<ipython-input-23-def399ad507c> in <module>()
----> 1 auth_url = credentials_1['auth_url']+"/v3"
      2 container = credentials_1['container']
      3 IBM_Objectstorage_Connection = swiftclient.Connection(
      4     key=credentials_1['password'], authurl=auth_url, auth_version='3', os_options={
      5         "project_id": credentials_1['project_id'], "user_id": credentials_1['user_id'], "region_name": credentials_1['region']})

KeyError: 'auth_url'

**Comment by balajikadambi** [comment]
Hi,

It appears that the credentials_1 does not have the field 'auth_url'.
credentials_1 = {
  'auth_url':'https://identity.open.softlayer.com',
.......
}
Please check. If not, remove the credentials and insert again. Make sure the variable name is credentials_1.

Thanks,
Balaji

**Comment by meghamishra** [comment]
How to proceed here?


KeyErrorTraceback (most recent call last)
<ipython-input-11-7a948e1e4fba> in <module>()
      1 auth_url = credentials_1['auth_url']+"/v3"
----> 2 container = credentials_1["container"]
      3 
      4 IBM_Objectstorage_Connection = swiftclient.Connection(
      5     key=credentials_1['password'], authurl=auth_url, auth_version='3', os_options={

KeyError: 'container'

**Comment by balajikadambi** [comment]
Hi Megha,

Please check my earlier response. The credentials_1 variable does not seem to have the container field. 
Please try to add the credentials again and see.

Thanks,
Balaji

**Comment by meghamishra** [comment]
Ya I tried to add credentials again, still not found the container field.
Any idea where I might be going wrong?

**Comment by balajikadambi** [comment]
ok, please see if you get all the fields as shown below:
credentials_2 = {
  'auth_url':'https://identity.open.softlayer.com',
  'project':'----',
  'project_id':'------',
  'region':'dallas',
  'user_id':'---',
  'domain_id':'----',
  'domain_name':'---',
  'username':'----',
  'password':"""----""",
  'container':'',
  'filename':''
}

if not, please paste the credentials that has been inserted after removing password and other information.

Thanks,
Balaji

**Comment by meghamishra** [comment]
I have followed this completely: https://github.com/IBM/watson-document-classifier
I am still not able to figure out my mistake.
here are the credentials obtained by me:
    'IBM_API_KEY_ID': ....
    'IBM_SERIVCE_INSTANCE_ID': 
    'ENDPOINT': ...
    'IBM_AUTH_ENDPOINT': ...
    'BUCKET':...
    'FILE': 'sample_text.txt'

**Comment by balajikadambi** [comment]
You need to use "Open Stack Swift based Object Storage" for this pattern.

**Comment by idealsing** [comment]
i din't get any option to choose "swift based api" after signup. i am trying to compile sample program which has been provided in correlation topic

**Comment by balajikadambi** [comment]
This pattern has been updated with a modified notebook that uses the COS based IBM Cloud Object Storage. Closing issue. Please open a new issue if required.
