### ISSUE TITLE
Error in 2.3

### ISSUE THREAD

**Issue by idealsing** [IBM/watson-document-co-relation#16]
# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials_1 = {
    'IBM_API_KEY_ID': 'SwrwslFTRrPQZhBRcfxEMUppNrtpGiEBvaWOMtQUr6iO',
    'IAM_SERVICE_ID': 'iam-ServiceId-0e2b1a61-1eef-4c13-9a50-a765df76f36b',
    'ENDPOINT': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
    'IBM_AUTH_ENDPOINT': 'https://iam.ng.bluemix.net/oidc/token',
    'BUCKET': 'default2232ab05ca4324c5daa253e07d89dc38a',
    'FILE': 'sample_text_1.txt'
}
# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials_2 = {
    'IBM_API_KEY_ID': 'SwrwslFTRrPQZhBRcfxEMUppNrtpGiEBvaWOMtQUr6iO',
    'IAM_SERVICE_ID': 'iam-ServiceId-0e2b1a61-1eef-4c13-9a50-a765df76f36b',
    'ENDPOINT': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
    'IBM_AUTH_ENDPOINT': 'https://iam.ng.bluemix.net/oidc/token',
    'BUCKET': 'default2232ab05ca4324c5daa253e07d89dc38a',
    'FILE': 'sample_text_2.txt'
}

The above cell is executing properly but i am facing issues while compiling next cell. kindly provide solution as early as possible

 # Specify file names for sample text and configuration files
sampleTextFileName1 = "sample_text_1.txt"
sampleTextFileName2 = "sample_text_2.txt"
sampleConfigFileName = "sample_config.txt"

# Maintain tagged text and plain text map
tagTextMap ={}

# Stop words
stopWords = stopwords.words('english')
# Additional words to be ignored 
stopWords.extend(["The","This","That",".","!","?"])

//ERROR I AM GETTING
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/nltk/corpus/util.py in __load(self)
     79             except LookupError as e:
---> 80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
     81                 except LookupError: raise e

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/nltk/data.py in find(resource_name, paths)
    672     resource_not_found = '\n%s\n%s\n%s\n' % (sep, msg, sep)
--> 673     raise LookupError(resource_not_found)
    674 

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  Searched in:
    - '/home/dsxuser/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/conda/envs/DSX-Python35/nltk_data'
    - '/opt/conda/envs/DSX-Python35/lib/nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

LookupError                               Traceback (most recent call last)
<ipython-input-30-b6450963ca4d> in <module>()
      8 
      9 # Stop words
---> 10 stopWords = stopwords.words('english')
     11 # Additional words to be ignored
     12 stopWords.extend(["The","This","That",".","!","?"])

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/nltk/corpus/util.py in __getattr__(self, attr)
    114             raise AttributeError("LazyCorpusLoader object has no attribute '__bases__'")
    115 
--> 116         self.__load()
    117         # This looks circular, but its not, since __load() changes our
    118         # __class__ to something new:

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/nltk/corpus/util.py in __load(self)
     79             except LookupError as e:
     80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
---> 81                 except LookupError: raise e
     82 
     83         # Load the corpus.

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/nltk/corpus/util.py in __load(self)
     76         else:
     77             try:
---> 78                 root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
     79             except LookupError as e:
     80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/nltk/data.py in find(resource_name, paths)
    671     sep = '*' * 70
    672     resource_not_found = '\n%s\n%s\n%s\n' % (sep, msg, sep)
--> 673     raise LookupError(resource_not_found)
    674 
    675 

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  Searched in:
    - '/home/dsxuser/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/conda/envs/DSX-Python35/nltk_data'
    - '/opt/conda/envs/DSX-Python35/lib/nltk_data'
**********************************************************************

**Comment by idealsing** [comment]
https://github.com/IBM/watson-document-co-relation/tree/master/notebooks
you can see the source code here

**Comment by balajikadambi** [comment]
Hi, 

You are using IBM Cloud Object Storage. You might  need to modify the code a bit to retrieve files from the Cloud Object Storage.

Please refer to the HowTo to see how to use IBM Cloud Object Storage from DSX.
https://developer.ibm.com/code/howtos/ibm-cloud-object-storage-usage-ibm-datascience-experience

Thanks,
Balaji

**Comment by idealsing** [comment]
tutorial









# @hidden_cell
credentials_1 = {
  'auth_url':'',
  'project':'',
  'project_id':'',
  'region':'',
  'user_id':'',
  'domain_id':'',
  'domain_name':'',
  'username':'',
  'password':"",
  'container':'',
  'filename':''
}

tutorial shows to import credentials in above way but i got credentials in different way as below
credentials_1 = {
'IBM_API_KEY_ID': 'SwrwslFTRrPQZhBRcfxEMUppNrtpGiEBvaWOMtQUr6iO',
'IAM_SERVICE_ID': 'iam-ServiceId-0e2b1a61-1eef-4c13-9a50-a765df76f36b',
'ENDPOINT': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
'IBM_AUTH_ENDPOINT': 'https://iam.ng.bluemix.net/oidc/token',
'BUCKET': 'default2232ab05ca4324c5daa253e07d89dc38a',
'FILE': 'sample_text_1.txt'
}

**Comment by alexsolovey** [comment]
I got the same error in 2.3 cell, but it is easy to fix. 
Edit the cell to insert nltk.download('stopwords') line under # Stop words section:

# Stop words
nltk.download('stopwords')
stopWords = stopwords.words('english')

After that rerun the cell.

**Comment by idealsing** [comment]
ya 2.3 error solved but in 5 cell error occurs

ClientExceptionTraceback (most recent call last)
<ipython-input-15-8028cd8e065e> in <module>()
----> 1 text1 = get_object(container, sampleTextFileName1)
      2 text2 = get_object(container, sampleTextFileName2)
      3 config = get_object(container, sampleConfigFileName)
      4 
      5 relationships = []

<ipython-input-14-def399ad507c> in get_object(container_name, fname)
     19 def get_object(container_name, fname):
     20     Object_Store_file_details = IBM_Objectstorage_Connection.get_object(
---> 21         container_name, fname)
     22     return Object_Store_file_details[1]

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in get_object(self, container, obj, resp_chunk_size, query_string, response_dict, headers)
   1784                                      query_string=query_string,
   1785                                      response_dict=response_dict,
-> 1786                                      headers=headers)
   1787         is_not_range_request = (
   1788             not headers or 'range' not in (k.lower() for k in headers))

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in _retry(self, reset_func, func, *args, **kwargs)
   1664             try:
   1665                 if not self.url or not self.token:
-> 1666                     self.url, self.token = self.get_auth()
   1667                     self.http_conn = None
   1668                 if self.service_auth and not self.service_token:

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in get_auth(self)
   1616                                         cert=self.cert,
   1617                                         cert_key=self.cert_key,
-> 1618                                         timeout=self.timeout)
   1619         return self.url, self.token
   1620 

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in get_auth(auth_url, user, key, **kwargs)
    661             if auth_version in AUTH_VERSIONS_V2:
    662                 raise ClientException('No tenant specified')
--> 663             raise ClientException('No project name or project id specified.')
    664 
    665         storage_url, token = get_auth_keystone(auth_url, user,

ClientException: No project name or project id specified.

ClientExceptionTraceback (most recent call last)
<ipython-input-15-8028cd8e065e> in <module>()
----> 1 text1 = get_object(container, sampleTextFileName1)
      2 text2 = get_object(container, sampleTextFileName2)
      3 config = get_object(container, sampleConfigFileName)
      4 
      5 relationships = []

<ipython-input-14-def399ad507c> in get_object(container_name, fname)
     19 def get_object(container_name, fname):
     20     Object_Store_file_details = IBM_Objectstorage_Connection.get_object(
---> 21         container_name, fname)
     22     return Object_Store_file_details[1]

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in get_object(self, container, obj, resp_chunk_size, query_string, response_dict, headers)
   1784                                      query_string=query_string,
   1785                                      response_dict=response_dict,
-> 1786                                      headers=headers)
   1787         is_not_range_request = (
   1788             not headers or 'range' not in (k.lower() for k in headers))

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in _retry(self, reset_func, func, *args, **kwargs)
   1664             try:
   1665                 if not self.url or not self.token:
-> 1666                     self.url, self.token = self.get_auth()
   1667                     self.http_conn = None
   1668                 if self.service_auth and not self.service_token:

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in get_auth(self)
   1616                                         cert=self.cert,
   1617                                         cert_key=self.cert_key,
-> 1618                                         timeout=self.timeout)
   1619         return self.url, self.token
   1620 

/usr/local/src/bluemix_jupyter_bundle.v81/notebook/lib/python2.7/site-packages/swiftclient/client.pyc in get_auth(auth_url, user, key, **kwargs)
    661             if auth_version in AUTH_VERSIONS_V2:
    662                 raise ClientException('No tenant specified')
--> 663             raise ClientException('No project name or project id specified.')
    664 
    665         storage_url, token = get_auth_keystone(auth_url, user,

ClientException: No project name or project id specified

**Comment by balajikadambi** [comment]
Please use the new notebook. Closing issue. Please open a new issue if required.
