### ISSUE TITLE
Missing version in cell 2.1

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-document-co-relation#2]
The Notebook cell for 2.1 does not contain a version, nor does it specify how/which version to add.
I believe that is why my notebook fails with missing data in cell #5:

<img width="831" alt="screen shot 2017-09-21 at 10 14 56 am" src="https://user-images.githubusercontent.com/14651388/30706563-ef214a1c-9eb5-11e7-8c2f-fa68889c9f89.png">

**Comment by scottdangelo** [comment]
after the above warnings:
<img width="974" alt="screen shot 2017-09-21 at 10 45 43 am" src="https://user-images.githubusercontent.com/14651388/30707890-21f1410a-9eba-11e7-96da-ca5c6ab2e5db.png">

**Comment by scottdangelo** [comment]
Adding a version (i.e. 2017-02-27) fixes this.
It could be hard-coded, or the user should be instructed to add it.

**Comment by balajikadambi** [comment]
I have added the version '2017-02-27' for Watson NLU credentials.

**Comment by stevemart** [comment]
@balajikadambi please use pull requests rather than committing directly to master. thanks for the fix though!
